import Layout from '@/comps/layout'
import Poster from '@/comps/poster'
import Head from 'next/head'
import { useEffect, useState } from 'react'

export default function Home() {

  const [data , setData] = useState<any | null>(null); 
  return (
    <>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/insta.ico" />
      </Head>
      <Layout>
      </Layout>
    </>
  )
}
